### ISSUE TITLE
Undefined devices

### ISSUE THREAD

**Issue by nascentt** [manish001in/pushbridge#4]
For a new install of pushbridge and after adding a token many undefined devices show (still true for 1.2.5)

<img width="428" height="637" alt="Image" src="https://github.com/user-attachments/assets/4bf2e411-1a0f-4fcf-a743-621a59a59543" />

**Comment by nascentt** [comment]
after looking at https://api.pushbullet.com/v2/devices
i see all the devices that correspond with "undefined" are all active: false in the api:

    {
      "active": false,
      "iden": "*vfcHY5HJKNB00O383TF",
      "created": 1609620292.120735,
      "modified": 1705168462.666206,
      "pushable": false,
      "icon": "phone"
    },
so i think just filtering thise out is enough to solve that.

**Comment by manish001in** [comment]
Fixed in latest release! Please check! 1.2.7

**Comment by nascentt** [comment]
Thanks for the fix, although funnily enough I now cant see any devices in the context menu:

<img width="390" height="148" alt="Image" src="https://github.com/user-attachments/assets/7c821bdd-01db-4992-bf9d-f161999f719d" />

I do see them in the extention options though

<img width="537" height="274" alt="Image" src="https://github.com/user-attachments/assets/13a1f929-ca61-4a7b-b515-22cf3f338169" />

**Comment by manish001in** [comment]
damn! yeah! the issue was fixed but ver bump caused this. i have bumped the version to 1.3.0. its showing the right devices in my list :) hope it fixes the issue for you. thank you for helping me chase down these issues

**Comment by nascentt** [comment]
So I'm using 1.3.0 and still don't see any devices in the context menu.
I see them all in the options dialog though.

<img width="310" height="160" alt="Image" src="https://github.com/user-attachments/assets/d8d9d8f0-ee45-421e-91d7-5a7a892e1eed" />

<img width="535" height="283" alt="Image" src="https://github.com/user-attachments/assets/a1c4e221-758a-438f-bd2b-f4ab753b9f23" />
